.\" SCCS ID: xfbd.1 3.0.0 12/06/1999
.TH xfce 1F "Olivier Fourdan"
.SH NAME
xfmouse \- Mouse configurator for "The Cholesterol Free Desktop Environment"
.SH SYNOPSYS
.B xfmouse
[--display] [-i]
.PP
.BI \--display " host:dpy"
.PP
specifies the server to connect to.
.PP
.TP 6
.BI \-i 
Starts up xfmouse with its graphical user interface.
.PP
.SH DESCRIPTION
xfmouse provides an easy and elegant way of managing mouse settings (left/right
handed, acceleration, threshold).
xfmouse can be started from xfwm configuration scripts and it silently applies user 
selected parameters at startup.
.PP
If xfmouse is started with the option 
.I -i
the graphical user interface of xfmouse is displayed.
.PP
.SH FILES
.PP
.I ~/.xfmouserc
contains the user preferences for mouse settings.
.PP
.SH SEE ALSO
xfce, xftree, xfwm, xfpager, xfsound, xfmouse, xfbd, xfclock
.PP
.SH AUTHOR
Olivier Fourdan (fourdan@xfce.org)
.PP
