.\" SCCS ID: xfrun.1 3.5.1 06/09/2000

.TH xfce 1F "Olivier Fourdan"
.SH NAME
xfrun \- laucher
.SH SYNOPSYS
.B xfrun
.PP
.SH DESCRIPTION
xfrun prompts user for a command and runs it.
.SH SEE ALSO
xfce, xftree, xfwm, xfpager, xfsound, xfhelp, xfbd, xfclock
.PP
.SH AUTHOR
Olivier Fourdan (fourdan@xfce.org)
.PP
